---
- name: Generate SSH key for user {{sudo_user}}
  user:
    name: "{{sudo_user}}"
    generate_ssh_key: yes
    ssh_key_type: "{{ssh_key_type}}"
    ssh_key_passphrase: "{{sudo_ssh_passphrase}}"
    ssh_key_file: "~/.ssh/{{ssh_key_profile}}-{{ssh_key_type}}"
    ssh_key_comment: "{{ssh_key_profile}} key"
  # shell:
  #   cmd: ssh-keygen -q -t {{ssh_key_type}} -N "{{sudo_ssh_passphrase}}" -f "~/.ssh/{{ssh_key_profile}}-{{ssh_key_type}}" -C "{{ssh_key_profile}} key"
  #   creates: "~/.ssh/{{ssh_key_profile}}-{{ssh_key_type}}"
