# reference: https://github.com/vitalk/ansible-secure-ssh/
---
- name: Add identity key to authorized keys on host
  authorized_key:
    user: "{{ ssh_user }}"
    key: "{{ lookup('file', ssh_identity_key) }}"
  register: add_identity_key
  when: ssh_identity_key is defined and ssh_user is defined
  # alternatively
  # shell:
  #   cmd: cat {{ssh_filename}}.pub >> ~/.ssh/authorized_keys

- name: Disable empty password login
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "^((?:(?!#).)*?|^#\\s?)PermitEmptyPasswords\\s(yes|no)"
    line: "PermitEmptyPasswords no"
  notify: restart sshd
  # consider: ^#?PermitEmptyPasswords

- name: Disable remote root login
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "^((?:(?!#).)*?|^#\\s?)PermitRootLogin "
    line: "PermitRootLogin no"
  notify: restart sshd
  # consider "^#?PermitRootLogin "

- name: Disable password login
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^((?:(?!#).)*?|^#\\s?)PasswordAuthentication\\s(yes|no)'
    line: "PasswordAuthentication no"
  when:
    - add_identity_key is succeeded
    - not add_identity_key is skipped
  notify: restart sshd
  # consider: "^(#  *)?PermitRootLogin (yes|no)"
  # consider: "^(#\s*)?PasswordAuthentication "

- name: Disable challenge response authentication
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^((?:(?!#).)*?|^#\\s?)ChallengeResponseAuthentication\\s(yes|no)'
    line: "ChallengeResponseAuthentication no"
  when:
    - add_identity_key is succeeded
    - not add_identity_key is skipped
  notify: restart sshd
  # consider: "^(#\s*)?ChallengeResponseAuthentication "

- name: Enable PAM
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "^((?:(?!#).)*?|^#\\s?)^#?UsePAM\\s(yes|no)"
    line: "UsePAM yes"
  notify: restart sshd
  # consider: "^#?UsePAM "
