---
- name: "update | repositories"
  ansible.builtin.package:
    update_cache: true
    cache_valid_time: 3600

- name: "update | upgrade"
  ansible.builtin.package:
    upgrade: dist
  register: upgrade
  retries: 5
  delay: 2
  until: upgrade is success
