---
- name: "Update | Will update only if OS: Ubuntu, Debian"
  become: true
  block:
  - name: "Update |  Update repositories"
    apt:
      update_cache: true
      cache_valid_time: 3600

  - name: "Update | Upgrade packages"
    apt:
      upgrade: dist
    register: upgrade
    retries: 5
    delay: 2
    until: upgrade is success

  - name: "Update | Cleanup packages"
    apt:
      autoclean: true
      autoremove: true

  when: ansible_distribution in ["Ubuntu", "Debian"]
