---
- name: "update | apt"
  when: ansible_distribution in ["Ubuntu", "Debian"]
  become: true
  block:
    - name: "update | repositories"
      package:
        update_cache: true
        cache_valid_time: 3600

    - name: "update | upgrade"
      package:
        upgrade: dist
      register: upgrade
      retries: 5
      delay: 2
      until: upgrade is success

    - name: "update | cleanup"
      package:
        autoclean: true
        autoremove: true
