---
- name: "fail2ban"
  become: true
  vars:
    f2b_fail2ban_local_default_edits: |
      [DEFAULT]
      ignoreip = 127.0.0.1/8 ::1 {{ f2b_unbanned_ip }}
    f2b_jail_local_sshd_edits: |
      [sshd]
      enabled = true
      port = {{ ssh_port }}
      maxretry = 3
      bantime = 600
      filter = sshd
      logpath = /var/log/auth.log
      backend = systemd
  block:
    - name: "fail2ban | install"
      ansible.builtin.package:
        name: fail2ban
        state: latest

    - name: "fail2ban | when config files exist"
      block:
        - name: "fail2ban | copy settings"
          ansible.builtin.copy:
            remote_src: yes
            src: "/etc/fail2ban/{{ item.src }}"
            dest: "/etc/fail2ban/{{ item.dest }}"
          loop:
            - { src: fail2ban.conf, dest: fail2ban.local }
            - { src: jail.conf, dest: jail.local }
        
        - name: "fail2ban | edit fail2ban.local"
          ansible.builtin.lineinfile:
            state: present
            path: /etc/fail2ban/fail2ban.local
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
          loop:
            - { regexp: "^\\[DEFAULT\\]", line: "{{ f2b_fail2ban_local_default_edits }}" }
            - { regexp: "^loglevel", line: "loglevel = INFO" }
            - { regexp: "^logtarget", line: "logtarget = /var/log/fail2ban.log" }

        - name: "fail2ban | comments out in jail.local"
          ansible.builtin.replace:
            path: /etc/fail2ban/jail.local
            regexp: "(^\\[sshd\\][\\s\\S]*?)({{ item }})"
            replace: "\\1#{{ item }}"
          loop:
            - port
            - logpath
            - backend

        - name: "fail2ban | edit sshd in jail.local"
          ansible.builtin.lineinfile:
            state: present
            path: /etc/fail2ban/jail.local
            regexp: "^\\[sshd\\]"
            line: "{{ f2b_jail_local_sshd_edits }}"

        - name: "fail2ban | start fail2ban and ensure it starts on a fresh reboot."
          ansible.builtin.service:
            state: started
            name: fail2ban
            enabled: yes
      rescue:
        - name: "fail2ban | encountered an error"
          ansible.builtin.debug:
            msg: "Usually the error is that config files don't exist. Check. /etc/fail2ban/fail2ban.conf and jail.conf."
