---
- name: "lvm fix | resize"
  when: ansible_distribution == "Ubuntu"
  become: true
  lvol:
    vg: ubuntu-vg
    lv: ubuntu-lv
    size: +100%FREE
    resizefs: true
  register: lvol_exists
  ignore_errors: true

- name: "lvm fix | manage if no volume"
  debug: msg="{{ lvol_exists.msg }}"
  when: lvol_exists.failed
