---
- become: true
  name: "lvm fix | extend logical volume to consume all remaining space in the volume group"
  lvol:
    vg: ubuntu-vg
    lv: ubuntu-lv
    size: +100%FREE
    resizefs: true
  when: ansible_distribution == "Ubuntu"
  register: lvol_exists
  ignore_errors: true

- name: "lvm fix | manage if no volume"
  debug: msg="{{ lvol_exists.msg }}"
  when: lvol_exists.failed
