---
# Reference: https://github.com/bodsch/ansible-snapd

- name: "remove snap"
  become: true
  vars:
    snapd_files:
      - /snap
      - /var/snap
      - /var/lib/snapd
      - /var/cache/snapd
      - /run/snapd-snap.socket
      - /run/snapd.socket
      - /etc/apt/apt.conf.d/20snapd.conf
      - /usr/lib/snapd
      - ~/snap
  block:
    - name: "remove snap | shutdown services, sockets and timers"
      ansible.builtin.service:
        name: snapd
        state: stopped
        enabled: false
      failed_when: false

    - name: "remove snap | uninstall"
      ansible.builtin.package:
        name: snapd
        state: absent
        purge: true

    - name: "remove snap | block future installs"
      ansible.builtin.blockinfile:
        create: true
        dest: "/etc/apt/preferences.d/snapd.pref"
        mode: 0644
        block: |
          Package: snapd
          Pin: release *
          Pin-Priority: -1

    - name: "remove snap | remove directories"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ snapd_files }}"
      loop_control:
        label: "{{ item }}"
