---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html

- name: "super user | create user '{{ sudo_user }}'"
  become: true
  user:
    name: "{{ sudo_user }}"
    password: "{{ sudo_password }}"
    shell: /bin/bash
    groups: sudo
    state: present
    append: yes

- name: "super user | add to sudoers"
  linefile:
    create: true
    backup: yes
    path: "/etc/sudoers.d/{{ sudo_user }}"
    line: "{{ sudo_user }}  ALL=(ALL)  NOPASSWD: ALL"
    mode: 0440
    owner: root
    group: root
    validate: visudo -cf "/etc/sudoers.d/{{ sudo_user }}"
