---
- name: "timezone | {{ timezone }}"
  become: true
  community.general.timezone:
    name: "{{ timezone }}"
  register: timezone_changed

- name: "timezone | apply"
  when: timezone_changed.changed
  ansible.builtin.shell: dpkg-reconfigure -f noninteractive tzdata
