---
# Reference by: https://github.com/jnv/ansible-role-unattended-upgrades

- name: add distribution-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: add Debian Wheezy workaround
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  when: (ansible_distribution == "Debian") and (ansible_distribution_release == "wheezy")

- name: add Debian Bullseye workaround
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  when: (ansible_distribution == "Debian") and (ansible_distribution_release == "bullseye")

- name: Install unattended-upgrades
  package:
    name: unattended-upgrades
    state: present
    cache_valid_time: "{{ unattended_cache_valid_time }}"

- name: create APT auto-upgrades configuration
  template:
    src: auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: create unattended-upgrades configuration
  template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
