---
- name: "reboot | clean repositories"
  ansible.builtin.package:
    autoclean: true
    autoremove: true

- name: "reboot | install needrestart"
  ansible.builtin.package:
    name: needrestart
    state: present
  
- name: "reboot | run needrestart"
  ansible.builtin.shell: "needrestart -r a"

- name: "reboot | reboot?"
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: "reboot | reboot as needed"
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible because of reboot required file."
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: reboot_required.stat.exists

