---
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#   @file        :  playbook.yml
#   @description :  initial setup for servers, workstations, virtual or not
#   @usage       :  ansible-playbook playbook.yml \
#                                    -i hosts.yml \
#                                    --ask-become-pass \
#                                    --vault-password-file ~/.vault_key \
#                                    --limit [all or servers or workstations or localhost or 192.168.0.133] \
#                                    --tags [setup or update or ssh or 'empty']
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# plays for remote hosts
- name: server-plays
  hosts: servers
  roles:
    - role: common
      tags: [setup, update]
    - role: common_setup
      tags: [setup]
    - role: server_setup
      tags: [setup]
    - role: wrapit
      tags: [setup, update]

# plays for workstations and local machines
- name: workstation-plays
  hosts: workstations
  remote_user: "{{ guest_user }}"
  gather_facts: true
  # connection: local
  roles:
    - role: common
      tags: [setup, update]
    - role: common_setup
      tags: [setup]
    - role: workstation_setup
      tags: [setup]
    - role: wrapit
      tags: [setup, update]
