---
- name: "ssh | deploy ssh key"
  remote_user: "{{ ssh_user }}"
  authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/{{ the_ansible_ssh_filename }}') }}"

# - vars:
#     file_host: ~/.ssh/authorized_keys
#   name: "Keeping authorized keys sorted and unique"
#   shell: |
#     sort "{{ file_host }}" | uniq > "{{ file_host }}".uniq
#     cp "{{ file_host }}".uniq "{{ file_host }}"
