---
- name: Set timezone to "{{ timezone }}"
  become: true
  timezone:
    name: "{{ timezone }}"
  notify: restart timezone dependent services

- name: Reconfigure Timezone Data
  command: dpkg-reconfigure -f noninteractive tzdata
