---
- name: "ansible ssh key | create"
  become: true
  user:
    name: "{{ sudo_user }}"
    generate_ssh_key: yes
    ssh_key_type: "{{ the_ansible_ssh_key_type }}"
    ssh_key_passphrase: "{{ the_ansible_ssh_passphrase }}"
    ssh_key_file: ".ssh/{{ the_ansible_ssh_filename }}"
    ssh_key_comment: "{{ the_ansible_ssh_filename }} key"

# - name: "ansible ssh key | Keeping authorized keys sorted and unique"
#   vars:
#     file_host: ~/.ssh/known_hosts
#   shell: |
#     sort "{{ file_host }}" | uniq > "{{ file_host }}".uniq
#     cp "{{ file_host }}".uniq "{{ file_host }}"
