---
- vars:
    the_ansible_name: "{{ the_ansible_ssh_filename | regex_replace('^.*(?<=\\/)(?P<name>.*)(?=\\.)', '\\name') }}"
  name: "Generate SSH key for profile '{{ the_ansible_name }}'"
  user:
    name: "{{ the_ansible_name }}"
    generate_ssh_key: yes
    ssh_key_type: "{{ ssh_key_type }}"
    ssh_key_passphrase: "{{ the_ansible_ssh_passphrase }}"
    ssh_key_file: "{{ the_ansible_ssh_filename }}"
    ssh_key_comment: "{{ the_ansible_name }} key"

- vars:
    file_host: ~/.ssh/known_hosts
  name: "Keeping authorized keys sorted and unique"
  shell: |
    sort "{{ file_host }}" | uniq > "{{ file_host }}".uniq
    cp "{{ file_host }}".uniq "{{ file_host }}"
