---
- name: "install essential"
  become: true
  ansible.builtin.package:
    state: present
    name:
      - build-essential

- name: "install optional"
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ item }}"
  loop: "{{ optional_packages }}"
