---
- name: Ensure these packages are installed.
  become: true
  apt:
    name:
      - build-essential
      - needrestart
      # - pwgen
      # - resolvconf
      # - unbound
      - unzip
    state: latest
