---
- name: Seyup unbound.
  become: true
  block:
  - name: Install unbound.
    apt: unbound
    state: latest

  - name: Disable the systemd-resolve stub DNS resolver (replaced by unbound)..
    lineinfile:
      dest: /etc/systemd/resolved.conf
      regexp: '^#DNSStubListener='
      line: 'DNSStubListener=no'
      state: present
    notify:
      - restart systemd-resolved

  - name: Check if a reboot is needed for Debian-based systems
    stat:
      path: /var/run/reboot-required
    register: reboot_required
  
  handlers:
  - name: restart systemd-resolved
    service:
      name: systemd-resolved
      state: restarted
    when: reboot_required.stat.exists == false
