---
# Reference https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md

- name: "[zsh-autosuggestions] Install dependencies zsh, git"
  become: true
  apt:
    name: [zsh, git]
    state: present

- name: "[zsh-autosuggestions] Backup zsh configruation file (.zshrc)"
  copy:
    src: ~/.zshrc
    dest: ~/.zshrc.bak

- name: "[zsh-autosuggestions] Clone oh-my-zsh"
  command: "git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  args:
    creates: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: "[zsh-autosuggestions] Configure plugins in .zshrc"
  replace:
    path: "~/.zshrc"
    regexp: "(?:^(?:(?!#).)*?plugins=\\s*)(?:\\((.+)\\))"
    replace: "plugins=(\\1 zsh-autosuggestions)"
